name: box2d_flame
version: 1.0.0
description: A Dart 2D physics engine, port from the Java version, works for Web/Flutter
homepage: https://github.com/flame-engine/box2d.dart
dependencies:
  vector_math: '>=2.0.0 <3.0.0'
dev_dependencies:
  build_web_compilers: '>=2.12.0-dev.1 <3.0.0'
  build_runner: '>=1.6.2 <2.0.0'
environment:
  sdk: ">=2.3.0 <3.0.0"
